---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomodoro
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pomodoro
  template:
    metadata:
      labels:
        name: pomodoro
    spec:
      containers:
        - name: pomodoro-container
          image: registry.wiloon.com/pomodoro:v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pomodoro-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 10080
      targetPort: 80
      nodePort: 30080
  selector:
    name: pomodoro
