version: '3'

tasks:
  default:
    desc: List available tasks
    cmd: task --list

  install:
    desc: Install dependencies
    cmd: pnpm install

  test:
    desc: Run unit tests
    cmd: pnpm test

  e2e:
    desc: Run E2E tests
    cmd: pnpm e2e

  dev:
    desc: Start local dev server
    cmd: pnpm dev

  build:
    desc: Build for production
    cmd: pnpm build

  preview:
    desc: Preview production build locally
    deps: [build]
    cmd: pnpm preview
