version: '3'

tasks:
  default:
    desc: List available tasks
    cmd: task --list

  dev:
    desc: Start local dev server
    cmd: pnpm dev

  build:
    desc: Build for production
    cmd: pnpm build

  preview:
    desc: Preview production build locally
    deps: [build]
    cmd: pnpm preview
